{"name": "login with valid credentials -- @1.4 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[@id='content']//h2[text()='My Account']\"}\n  (Session info: chrome=129.0.6668.90); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7D81F9412+29090]\n\t(No symbol) [0x00007FF7D816E239]\n\t(No symbol) [0x00007FF7D802B1DA]\n\t(No symbol) [0x00007FF7D807EFE7]\n\t(No symbol) [0x00007FF7D807F23C]\n\t(No symbol) [0x00007FF7D80C97C7]\n\t(No symbol) [0x00007FF7D80A672F]\n\t(No symbol) [0x00007FF7D80C65A2]\n\t(No symbol) [0x00007FF7D80A6493]\n\t(No symbol) [0x00007FF7D80709D1]\n\t(No symbol) [0x00007FF7D8071B31]\n\tGetHandleVerifier [0x00007FF7D851871D+3302573]\n\tGetHandleVerifier [0x00007FF7D8564243+3612627]\n\tGetHandleVerifier [0x00007FF7D855A417+3572135]\n\tGetHandleVerifier [0x00007FF7D82B5EB6+801862]\n\t(No symbol) [0x00007FF7D817945F]\n\t(No symbol) [0x00007FF7D8174FB4]\n\t(No symbol) [0x00007FF7D8175140]\n\t(No symbol) [0x00007FF7D816461F]\n\tBaseThreadInitThunk [0x00007FFBA69C257D+29]\n\tRtlUserThreadStart [0x00007FFBA80AAF28+40]\n\n", "trace": "  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 53, in step_impl\n    loggedin=context.accountpage.account()\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BDDproject\\features\\pages\\AccountPage.py\", line 16, in account\n    return self.driver.find_element(By.XPATH,self.accountinfo).text\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given i goto the login website", "status": "passed", "start": 1728566739434, "stop": 1728566739699}, {"name": "And entering the username as \"345\" and password as \"$%^\"", "status": "passed", "start": 1728566739699, "stop": 1728566739843}, {"name": "And click on the login button", "status": "passed", "start": 1728566739843, "stop": 1728566744248}, {"name": "Then i should get logged in", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[@id='content']//h2[text()='My Account']\"}\n  (Session info: chrome=129.0.6668.90); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7D81F9412+29090]\n\t(No symbol) [0x00007FF7D816E239]\n\t(No symbol) [0x00007FF7D802B1DA]\n\t(No symbol) [0x00007FF7D807EFE7]\n\t(No symbol) [0x00007FF7D807F23C]\n\t(No symbol) [0x00007FF7D80C97C7]\n\t(No symbol) [0x00007FF7D80A672F]\n\t(No symbol) [0x00007FF7D80C65A2]\n\t(No symbol) [0x00007FF7D80A6493]\n\t(No symbol) [0x00007FF7D80709D1]\n\t(No symbol) [0x00007FF7D8071B31]\n\tGetHandleVerifier [0x00007FF7D851871D+3302573]\n\tGetHandleVerifier [0x00007FF7D8564243+3612627]\n\tGetHandleVerifier [0x00007FF7D855A417+3572135]\n\tGetHandleVerifier [0x00007FF7D82B5EB6+801862]\n\t(No symbol) [0x00007FF7D817945F]\n\t(No symbol) [0x00007FF7D8174FB4]\n\t(No symbol) [0x00007FF7D8175140]\n\t(No symbol) [0x00007FF7D816461F]\n\tBaseThreadInitThunk [0x00007FFBA69C257D+29]\n\tRtlUserThreadStart [0x00007FFBA80AAF28+40]\n\n", "trace": "  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 53, in step_impl\n    loggedin=context.accountpage.account()\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BDDproject\\features\\pages\\AccountPage.py\", line 16, in account\n    return self.driver.find_element(By.XPATH,self.accountinfo).text\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\cks_1\\PycharmProjects\\BehaveProject1\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1728566744248, "stop": 1728566744267}], "parameters": [{"name": "username", "value": "345"}, {"name": "password", "value": "$%^"}], "start": 1728566736392, "stop": 1728566746374, "uuid": "16d4e675-a5e2-40bf-bbbf-de2f8b2563f7", "historyId": "935e16ac371374fe0763c5d2a40e37c9", "fullName": "this is the login test feature: login with valid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "login1"}, {"name": "feature", "value": "this is the login test feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}